package com.transport.fleet.response;

import lombok.Data;

import java.util.Date;
import java.util.List;

@Data
public class FleetDriverVO {
    private Long rowId;
    private Integer updTick;
    private String driverId;
    private String driver;
    private int active;
    private String bptnum;
    private String lanmain;
    private String lansec;
    private String cry;
    private Date bir;
    private Date credattim;
    private Date upddattim;
    private byte[] auuid;
    private String creusr;
    private String updusr;
    private String bpaaddlig0;
    private String bpaaddlig1;
    private String bpaaddlig2;
    private String poscod;
    private String cty;
    private String mob;
    private String web;
    private String licenum;
    private Date licedat;
    private int licetyp;
    private Date validat;
    private String delivby;
    private Date lastvime;
    private String fcy;
    private String sat;
    private String tel0;
    private String tel1;
    private String tel2;
    private String tel3;
    private String tel4;
    private String xuser;
    private String xpwd;
    private String xpwd1;
    private int xsigcon;
    private int xcamcon;
    private int xper;
    private int xlgnflg;
    private String xbus;
    private String xloginseqno;
    private String xbadnum;
    private Date xadrdat;
    private String xdocno;
    private String xx10cGeox;
    private String xx10cGeoy;
    private String xlncstarttim;
    private String xlncdur;
    private String styzon;
    private int xpaycon;
    private String xuvycod;
    private int xskpcon;
    private int xrescon;
    private int xqtychgcon;
    private int xspotcon;
    private int xpickupcon;
    private int xsihcon;
    private int xlogflag;
    private String xmacadd;
    private int xdeposit;
    private int xgeocon;
    private int xnooftrips;
    private int xsalerep;
    private int xdriver;
    private int xdsd;
    private int xsalrout;
    private int xcondriv;
    private int x1cunion;
    private int x10cmon;
    private int x10ctues;
    private int x10cwed;
    private int x10cthu;
    private int x10cfri;
    private int x10csat;
    private int x10csun;
    private int x1coverhrs;
    private int xmaxhrsday;
    private int xmaxhrsweek;
    private int xdriverhrs;
    private int xallvehicle;
    private Date xuvystrdat;
    private Date xuvyenddat;
    private int xlonghaul;
    private String note;
    private int x10csup;
    private int x10csupflg;
    private List<Document> documentList;
    private List<VehicleTable> siteList;
    private List<VehicleTable> vehicleClassList;
    private List<UnavailableDays> unavailableDaysList;
    private byte[] image;
}
