package com.transport.fleet.model;

import lombok.Data;

import javax.persistence.*;
import java.lang.reflect.Field;
import java.util.Date;

@Entity
@Data
@Table(name = "XX10CDRIVER")
public class FleetDriver {
    @Id
    @Column(name = "ROWID")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long rowId;

    @Column(name = "UPDTICK_0")
    private Integer updTick;
    @Column(name = "DRIVERID_0")
    private String driverId;
    @Column(name = "DRIVER_0")
    private String driver;
    @Column(name = "ACTIVE_0")
    private int active;
    @Column(name = "BPTNUM_0")
    private String bptnum;
    @Column(name = "LANMAIN_0")
    private String lanmain;
    @Column(name = "LANSEC_0")
    private String lansec;
    @Column(name = "CRY_0")
    private String cry;
    @Column(name = "BIR_0")
    private Date bir;
    @Column(name = "CREDATTIM_0")
    private Date credattim;
    @Column(name = "UPDDATTIM_0")
    private Date upddattim;
    @Column(name = "AUUID_0")
    private byte[] auuid;
    @Column(name = "CREUSR_0")
    private String creusr;
    @Column(name = "UPDUSR_0")
    private String updusr;
    @Column(name = "BPAADDLIG_0")
    private String bpaaddlig0;
    @Column(name = "BPAADDLIG_1")
    private String bpaaddlig1;
    @Column(name = "BPAADDLIG_2")
    private String bpaaddlig2;
    @Column(name = "POSCOD_0")
    private String poscod;
    @Column(name = "CTY_0")
    private String cty;
    @Column(name = "MOB_0")
    private String mob;
    @Column(name = "WEB_0")
    private String web;
    @Column(name = "LICENUM_0")
    private String licenum;
    @Column(name = "LICEDAT_0")
    private Date licedat;
    @Column(name = "LICETYP_0")
    private int licetyp;
    @Column(name = "VALIDAT_0")
    private Date validat;
    @Column(name = "DELIVBY_0")
    private String delivby;
    @Column(name = "LASTVIME_0")
    private Date lastvime;
    @Column(name = "FCY_0")
    private String fcy;
    @Column(name = "SAT_0")
    private String sat;
    @Column(name = "TEL_0")
    private String tel0;
    @Column(name = "TEL_1")
    private String tel1;
    @Column(name = "TEL_2")
    private String tel2;
    @Column(name = "TEL_3")
    private String tel3;
    @Column(name = "TEL_4")
    private String tel4;
    @Column(name = "XUSER_0")
    private String xuser;
    @Column(name = "XPWD_0")
    private String xpwd;
    @Column(name = "XPWD1_0")
    private String xpwd1;
    @Column(name = "XSIGCON_0")
    private int xsigcon;
    @Column(name = "XCAMCON_0")
    private int xcamcon;
    @Column(name = "XPER_0")
    private int xper;
    @Column(name = "XLGNFLG_0")
    private int xlgnflg;
    @Column(name = "XBUS_0")
    private String xbus;
    @Column(name = "XLOGINSEQNO_0")
    private String xloginseqno;
    @Column(name = "XBADNUM_0")
    private String xbadnum;
    @Column(name = "XADRDAT_0")
    private Date xadrdat;
    @Column(name = "XDOCNO_0")
    private String xdocno;
    @Column(name = "XADRAUTCLS_0")
    private int xadrautcls0;
    @Column(name = "XADRAUTCLS_1")
    private int xadrautcls1;
    @Column(name = "XADRAUTCLS_2")
    private int xadrautcls2;
    @Column(name = "XADRAUTCLS_3")
    private int xadrautcls3;
    @Column(name = "XADRAUTCLS_4")
    private int xadrautcls4;
    @Column(name = "XADRAUTCLS_5")
    private int xadrautcls5;
    @Column(name = "XADRAUTCLS_6")
    private int xadrautcls6;
    @Column(name = "XADRAUTCLS_7")
    private int xadrautcls7;
    @Column(name = "XADRAUTCLS_8")
    private int xadrautcls8;
    @Column(name = "XADRAUTCLS_9")
    private int xadrautcls9;
    @Column(name = "XADRAUTCL1_0")
    private int xadrautcl10;
    @Column(name = "XADRAUTCL1_1")
    private int xadrautcl11;
    @Column(name = "XADRAUTCL1_2")
    private int xadrautcl12;
    @Column(name = "XADRAUTCL1_3")
    private int xadrautcl13;
    @Column(name = "XADRAUTCL1_4")
    private int xadrautcl14;
    @Column(name = "XADRAUTCL1_5")
    private int xadrautcl15;
    @Column(name = "XADRAUTCL1_6")
    private int xadrautcl16;
    @Column(name = "XADRAUTCL1_7")
    private int xadrautcl17;
    @Column(name = "XADRAUTCL1_8")
    private int xadrautcl18;
    @Column(name = "XADRAUTCL1_9")
    private int xadrautcl19;
    @Column(name = "XADRAUTCL2_0")
    private int xadrautcl20;
    @Column(name = "XADRAUTCL2_1")
    private int xadrautcl21;
    @Column(name = "XADRAUTCL2_2")
    private int xadrautcl22;
    @Column(name = "XADRAUTCL2_3")
    private int xadrautcl23;
    @Column(name = "XADRAUTCL2_4")
    private int xadrautcl24;
    @Column(name = "XADRAUTCL2_5")
    private int xadrautcl25;
    @Column(name = "XADRAUTCL2_6")
    private int xadrautcl26;
    @Column(name = "XADRAUTCL2_7")
    private int xadrautcl27;
    @Column(name = "XADRAUTCL2_8")
    private int xadrautcl28;
    @Column(name = "XADRAUTCL2_9")
    private int xadrautcl29;
    @Column(name = "XADRAUTCL3_0")
    private int xadrautcl30;
    @Column(name = "XADRAUTCL3_1")
    private int xadrautcl31;
    @Column(name = "XADRAUTCL3_2")
    private int xadrautcl32;
    @Column(name = "XADRAUTCL3_3")
    private int xadrautcl33;
    @Column(name = "XADRAUTCL3_4")
    private int xadrautcl34;
    @Column(name = "XADRAUTCL3_5")
    private int xadrautcl35;
    @Column(name = "XADRAUTCL3_6")
    private int xadrautcl36;
    @Column(name = "XADRAUTCL3_7")
    private int xadrautcl37;
    @Column(name = "XADRAUTCL3_8")
    private int xadrautcl38;
    @Column(name = "XADRAUTCL3_9")
    private int xadrautcl39;
    @Column(name = "XX10C_GEOX_0")
    private String xx10cGeox;
    @Column(name = "XX10C_GEOY_0")
    private String xx10cGeoy;
    @Column(name = "XLNCSTARTTIM_0")
    private String xlncstarttim;
    @Column(name = "XLNCDUR_0")
    private String xlncdur;
    @Column(name = "STYZON_0")
    private String styzon;
    @Column(name = "XPAYCON_0")
    private int xpaycon;
    @Column(name = "XUVYCOD_0")
    private String xuvycod;
    @Column(name = "XSKPCON_0")
    private int xskpcon;
    @Column(name = "XRESCON_0")
    private int xrescon;
    @Column(name = "XQTYCHGCON_0")
    private int xqtychgcon;
    @Column(name = "XSPOTCON_0")
    private int xspotcon;
    @Column(name = "XPICKUPCON_0")
    private int xpickupcon;
    @Column(name = "XSIHCON_0")
    private int xsihcon;
    @Column(name = "XLOGFLAG_0")
    private int xlogflag;
    @Column(name = "XMACADD_0")
    private String xmacadd;
    @Column(name = "XDEPOSIT_0")
    private int xdeposit;
    @Column(name = "XGEOCON_0")
    private int xgeocon;
    @Column(name = "XNOOFTRIPS_0")
    private int xnooftrips;
    @Column(name = "XSALEREP_0")
    private int xsalerep;
    @Column(name = "XDRIVER_0")
    private int xdriver;
    @Column(name = "XDSD_0")
    private int xdsd;
    @Column(name = "XSALROUT_0")
    private int xsalrout;
    @Column(name = "XFCY_0")
    private String xfcy0;
    @Column(name = "XFCY_1")
    private String xfcy1;
    @Column(name = "XFCY_2")
    private String xfcy2;
    @Column(name = "XFCY_3")
    private String xfcy3;
    @Column(name = "XFCY_4")
    private String xfcy4;
    @Column(name = "XFCY_5")
    private String xfcy5;
    @Column(name = "XFCY_6")
    private String xfcy6;
    @Column(name = "XFCY_7")
    private String xfcy7;
    @Column(name = "XFCY_8")
    private String xfcy8;
    @Column(name = "XFCY_9")
    private String xfcy9;
    @Column(name = "XCONDRIV_0")
    private int xcondriv;
    @Column(name = "X1CUNION_0")
    private int x1cunion;
    @Column(name = "X10CMON_0")
    private int x10cmon;
    @Column(name = "X10CTUES_0")
    private int x10ctues;
    @Column(name = "X10CWED_0")
    private int x10cwed;
    @Column(name = "X10CTHU_0")
    private int x10cthu;
    @Column(name = "X10CFRI_0")
    private int x10cfri;
    @Column(name = "X10CSAT_0")
    private int x10csat;
    @Column(name = "X10CSUN_0")
    private int x10csun;
    @Column(name = "X1COVERHRS_0")
    private int x1coverhrs;
    @Column(name = "XMAXHRSDAY_0")
    private int xmaxhrsday;
    @Column(name = "XMAXHRSWEEK_0")
    private int xmaxhrsweek;
    @Column(name = "XDRIVERHRS_0")
    private int xdriverhrs;
    @Column(name = "XALLVEHICLE_0")
    private int xallvehicle;
    @Column(name = "XUVYSTRDAT_0")
    private Date xuvystrdat;
    @Column(name = "XUVYENDDAT_0")
    private Date xuvyenddat;
    @Column(name = "XLONGHAUL_0")
    private int xlonghaul;
    @Column(name = "XVEHICLECLAS_0")
    private String xvehicleclas0;
    @Column(name = "XVEHICLECLAS_1")
    private String xvehicleclas1;
    @Column(name = "XVEHICLECLAS_2")
    private String xvehicleclas2;
    @Column(name = "XVEHICLECLAS_3")
    private String xvehicleclas3;
    @Column(name = "XVEHICLECLAS_4")
    private String xvehicleclas4;
    @Column(name = "XVEHICLECLAS_5")
    private String xvehicleclas5;
    @Column(name = "XVEHICLECLAS_6")
    private String xvehicleclas6;
    @Column(name = "XVEHICLECLAS_7")
    private String xvehicleclas7;
    @Column(name = "XVEHICLECLAS_8")
    private String xvehicleclas8;
    @Column(name = "XVEHICLECLAS_9")
    private String xvehicleclas9;
    @Column(name = "NOTE_0")
    private String note;
    @Column(name = "X10CSUP_0")
    private int x10csup;
    @Column(name = "X10CSUPFLG_0")
    private int x10csupflg;

    @PrePersist
    @PreUpdate
    public void setDefaultValues() throws IllegalAccessException {
        Field[] columns = this.getClass().getDeclaredFields();
        for(Field column: columns){
            column.setAccessible(true);
            if(column.get(this)==null && !column.getName().equalsIgnoreCase("ROWID")){
                if(column.getType().equals(String.class)){
                    column.set(this, "");
                }else if(column.getType().equals(Integer.class)){
                    column.set(this, 0);
                }else if(column.getType().equals(Double.class)){
                    column.set(this, 0.0);
                }else if(column.getType().equals(Date.class)){
                    column.set(this, new Date());
                }else if(column.getType().equals(byte[].class)){
                    column.set(this, new byte[]{0});
                }
            }
        }
    }
}
