package com.transport.tracking.response;


import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Date;

@Getter
@Setter
@JsonInclude(JsonInclude.Include.NON_NULL)
public class FacilityVO {

      private int updtick;
      private String fcy;
      private String fcynam;
      private String fcysho;
      private String cry;
      private String crn;
      private String naf;
      private String bptnum;
      private Short mfgflg;
      private Short salflg;
      private Short purflg;
      private Short wrhflg;
      private Short finflg;
      private String finrspfcy;
      private Short dadflg;
      private String payban;
      private String legcpy;
      private String leg;
      private String bpaadd;
      private String bidnum;
      private String cntnam;
      private String dadfcy;
      private String acccod;
      private String creusr;
      private Date credat;
      private String updusr;
      private Date upddat;
      private Date credattim;
      private Date upddattim;
      private byte[] auuid;
      private String geocod;
      private Short oricerflg;
      private String rexnum;
      private String die;
      private String die_1;
      private String die_2;
      private String die_3;
      private String die_4;
      private String die_5;
      private String die_6;
      private String die_7;
      private String die_8;
      private String die_9;
      private String die_10;
      private String die_11;
      private String die_12;
      private String die_13;
      private String die_14;
      private String die_15;
      private String die_16;
      private String die_17;
      private String die_18;
      private String die_19;
      private String insctyflg;
      private String cce;
      private String cce_1;
      private String cce_2;
      private String cce_3;
      private String cce_4;
      private String cce_5;
      private String cce_6;
      private String cce_7;
      private String cce_8;
      private String cce_9;
      private String cce_10;
      private String cce_11;
      private String cce_12;
      private String cce_13;
      private String cce_14;
      private String cce_15;
      private String cce_16;
      private String cce_17;
      private String cce_18;
      private String cce_19;
      private Short uvyday;
      private Short uvyday_1;
      private Short uvyday_2;
      private Short uvyday_3;
      private Short uvyday_4;
      private Short uvyday_5;
      private Short uvyday_6;
      private String uvycod;
      private Short ivyflg;
      private String ivyfcy;
      private Short wrhges;
      private String rcpwrh;
      private String mfpwrh;
      private String trawrh;
      private String rtnwrh;
      private String mfrwrh;
      private String shiwrh;
      private String mfgwrh;
      private String trfwrh;
      private String scowrh;
      private String sccwrh;
      private String xx10c_geox;
      private Short spaopeigic;
      private String xx10c_geoy;
      private String strhou;
      private String endhou;
      private Short payflg;
      private Short hrmdadflg;
      private String hrmdadfcy;
      private String bpasge;
      private String bpadcl;
      private String cntdds;
      private String codcra;
      private Short regprh;
      private String prf;
      private String srv;
      private String cllcvt;
      private String rskwrk;
      private String hrmpayban;
      private Short hrmtaxwag;
      private Short secprh;
      private Short flgapp;
      private Short flgfor;
      private Short flgpec;
      private String chef;
      private String x1;
      private BigDecimal rowid;
}
